### ISSUE TITLE
Player working but can't access its functions

### ISSUE THREAD

**Issue by gestadieu** [Rafostar/media-player-controller#1]
Hi,
first thank you for this package, it is exactly what I needed for a project on a raspberry pi 4 and I can't see anything else similar.
I do have a problem however: I can create a player object and play a video with the opts.media parameters (on mpv or vlc), however I cannot use any method. 
Whatever I am using:

```js
player.load("videos/1-01.mp4");
player.setFullscreen(true);
player.setVolume(50);
player.keepOpen(true);
```

I always have something like:
player.setFullscreen(true);
        ^
TypeError: player.setFullscreen is not a function

When I use player.load(), I have the following error:
this._load(media, (err) =>
                     ^
TypeError: this._load is not a function
    at PlayerController.load

Is there anything wrong on what I am doing?

**Comment by Rafostar** [comment]
@gestadieu 

Thanks for taking interest in this module. I originally made it for just one other RPi streaming media node app I made, so the readme is quite lacking and should be updated, sorry about that.

Anyway, the functions are asynchronous and should be available only once player launches (we cannot send command to player that is not running). I have not seen your usage example, so I guess that you made something like:

```javascript
// Wrong
player.launch(err => {});
player.setFullscreen(true);
```

Since functions are asynchronous they are executed both, while the second one should be after launch.

```javascript
// Correct
player.launch(err => {
  player.setFullscreen(true);
});
```

There is also a `playback-started` event that I recommend using, as `vlc` can be controlled only after it occurs (a little later than `mpv`).

What you wanted to do is start in fullscreen with volume at 50%. You can either put that logic after `playback-started` event (to make it universal with both media players) or in case of `mpv` it can be right after launch too, but you can also simply launch with passing command line args to player (please note that those might be different per media player).

Check if this example is working for you (it should pause after start and resume after 5 sec):

```javascript
const PlayerController = require('media-player-controller');

var player = new PlayerController({
  app: 'mpv',
  media: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  args: ['--fullscreen', '--keep-open=yes', '--volume=50']
});

player.launch(err => {
  if(err) {
    return console.error(err.message);
  }
});

player.on('playback-started', () => {
  player.pause();
  setTimeout(() => player.play(), 5000);
});

player.on('playback', console.log);
```

**Comment by gestadieu** [comment]
stupid me! of course it is asynchronous, I did not even thing about it ;-)
Big thank you.
